version: '3.1'
services:
  db:
    image: mysql
    container_name: springboot_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - spring_data:/var/lib/msql

volumes:
  spring_data: